//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarSystem.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class AraclarListesi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AraclarListesi()
        {
            this.KiralamaIslemleri = new HashSet<KiralamaIslemleri>();
        }
    
        public int AracID { get; set; }
        public string Plaka { get; set; }
        public string Marka { get; set; }
        public string Seri { get; set; }
        public string Model_Yıl { get; set; }
        public int Km { get; set; }
        public string Vites { get; set; }
        public string Yakıt { get; set; }
        public int KiraUcreti { get; set; }
        public string Durum { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KiralamaIslemleri> KiralamaIslemleri { get; set; }
    }
}
