//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarSystem.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenelToplam
    {
        public int GenelToplamID { get; set; }
        public int GenelToplamUcret { get; set; }
    }
}
