//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarSystem.ENTITY
{
    using System;
    using System.Collections.Generic;
    
    public partial class KiralamaIslemleri
    {
        public int IslemID { get; set; }
        public int AracID { get; set; }
        public int MusteriID { get; set; }
        public System.DateTime AracCıkısTarihi { get; set; }
        public System.DateTime AracTeslimTarihi { get; set; }
        public int ToplamUcret { get; set; }
    
        public virtual AraclarListesi AraclarListesi { get; set; }
        public virtual Musteriler Musteriler { get; set; }
    }
}
