//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentCarSystem.ENTITY
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AracKiralamaEntities : DbContext
    {
        public AracKiralamaEntities()
            : base("name=AracKiralamaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AraclarListesi> AraclarListesi { get; set; }
        public virtual DbSet<GenelToplam> GenelToplam { get; set; }
        public virtual DbSet<KiralamaIslemleri> KiralamaIslemleri { get; set; }
        public virtual DbSet<Kullanıcılar> Kullanıcılar { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
    }
}
